// =============================================
//  KNGL RP — YAYINCI LİSTESİ
//
//  Düzenlemek için sadece şu iki alanı doldur:
//  - character:  RP'deki karakter adı
//  - role:       RP mesleği / rolü
//
//  Yeni yayıncı eklemek için bir bloğu
//  kopyalayıp en alta yapıştır, id'yi değiştir.
// =============================================

const STREAMERS = [
  {
    id: "s1",
    channelName: "6bir",
    character: "", // ← karakter adı
    platform: "kick",
    channelId: "alcaaf",
    profileUrl: "https://kick.com/alcaaf",
    avatar: "",
    role: "", // ← RP mesleği
  },
  {
    id: "s2",
    channelName: "BlackAttack",
    character: "",
    platform: "kick",
    channelId: "blackattack",
    profileUrl: "https://kick.com/blackattack",
    avatar: "",
    role: "",
  },
  {
    id: "s3",
    channelName: "F q X",
    character: "",
    platform: "kick",
    channelId: "fqxdev",
    profileUrl: "https://kick.com/fqxdev",
    avatar: "",
    role: "",
  },
  {
    id: "s4",
    channelName: "Kaiserlv",
    character: "",
    platform: "kick",
    channelId: "ka1serlv",
    profileUrl: "https://kick.com/ka1serlv",
    avatar: "",
    role: "",
  },
  {
    id: "s5",
    channelName: "ghost",
    character: "",
    platform: "kick",
    channelId: "mhrmexe",
    profileUrl: "https://kick.com/mhrmexe",
    avatar: "",
    role: "",
  },
  {
    id: "s6",
    channelName: "eren",
    character: "",
    platform: "kick",
    channelId: "erenb4rut",
    profileUrl: "https://kick.com/erenb4rut",
    avatar: "",
    role: "",
  },
  {
    id: "s7",
    channelName: "Yiğit",
    character: "",
    platform: "kick",
    channelId: "yyiido",
    profileUrl: "https://kick.com/yyiido",
    avatar: "",
    role: "",
  },
  {
    id: "s8",
    channelName: "Filozof",
    character: "",
    platform: "kick",
    channelId: "filozoff",
    profileUrl: "https://kick.com/filozoff",
    avatar: "",
    role: "",
  },
  {
    id: "s9",
    channelName: "slueash",
    character: "",
    platform: "kick",
    channelId: "slueash",
    profileUrl: "https://kick.com/slueash",
    avatar: "",
    role: "",
  },
  {
    id: "s10",
    channelName: "aksi",
    character: "",
    platform: "kick",
    channelId: "aksi45",
    profileUrl: "https://kick.com/aksi45",
    avatar: "",
    role: "",
  },
  {
    id: "s11",
    channelName: "Liyonn",
    character: "",
    platform: "kick",
    channelId: "liyoonn",
    profileUrl: "https://kick.com/liyoonn",
    avatar: "",
    role: "",
  },
  {
    id: "s12",
    channelName: "KoCaBeBe",
    character: "",
    platform: "kick",
    channelId: "kocabebe",
    profileUrl: "https://kick.com/kocabebe",
    avatar: "",
    role: "",
  },
  {
    id: "s13",
    channelName: "AdemBabush",
    character: "",
    platform: "kick",
    channelId: "adembabush",
    profileUrl: "https://kick.com/adembabush",
    avatar: "",
    role: "",
  },
  {
    id: "s14",
    channelName: "WallLizards",
    character: "",
    platform: "kick",
    channelId: "walllizards",
    profileUrl: "https://kick.com/walllizards",
    avatar: "",
    role: "",
  },
  {
    id: "s15",
    channelName: "SF Datssi",
    character: "",
    platform: "kick",
    channelId: "sfdatssi",
    profileUrl: "https://kick.com/sfdatssi",
    avatar: "",
    role: "",
  },
  {
    id: "s16",
    channelName: "Albert",
    character: "",
    platform: "kick",
    channelId: "albert361",
    profileUrl: "https://kick.com/albert361",
    avatar: "",
    role: "",
  },
  {
    id: "s17",
    channelName: "KEBU",
    character: "",
    platform: "kick",
    channelId: "kebu7",
    profileUrl: "https://kick.com/kebu7",
    avatar: "",
    role: "",
  },
  {
    id: "s18",
    channelName: "Cappture",
    character: "",
    platform: "kick",
    channelId: "cappture",
    profileUrl: "https://kick.com/cappture",
    avatar: "",
    role: "",
  },
  {
    id: "s19",
    channelName: "EzoM",
    character: "",
    platform: "kick",
    channelId: "iezom",
    profileUrl: "https://kick.com/iezom",
    avatar: "",
    role: "",
  },
  {
    id: "s20",
    channelName: "elworry",
    character: "",
    platform: "kick",
    channelId: "elworry",
    profileUrl: "https://kick.com/elworry",
    avatar: "",
    role: "",
  },
  {
    id: "s21",
    channelName: "Emircan",
    character: "",
    platform: "kick",
    channelId: "emircann",
    profileUrl: "https://kick.com/emircann",
    avatar: "",
    role: "",
  },
  {
    id: "s22",
    channelName: "buluch",
    character: "",
    platform: "kick",
    channelId: "buluch",
    profileUrl: "https://kick.com/buluch",
    avatar: "",
    role: "",
  },
  {
    id: "s23",
    channelName: "Tosun",
    character: "",
    platform: "kick",
    channelId: "adimtosundeil",
    profileUrl: "https://kick.com/adimtosundeil",
    avatar: "",
    role: "",
  },
  {
    id: "s24",
    channelName: "Ayberk",
    character: "",
    platform: "kick",
    channelId: "ayberk",
    profileUrl: "https://kick.com/ayberk",
    avatar: "",
    role: "",
  },
  {
    id: "s25",
    channelName: "Chemosh",
    character: "",
    platform: "kick",
    channelId: "chemossh",
    profileUrl: "https://kick.com/chemossh",
    avatar: "",
    role: "",
  },
  {
    id: "s26",
    channelName: "Vidar",
    character: "",
    platform: "kick",
    channelId: "vidaaarr",
    profileUrl: "https://kick.com/vidaaarr",
    avatar: "",
    role: "",
  },
  {
    id: "s27",
    channelName: "SOLEM0",
    character: "",
    platform: "kick",
    channelId: "solem0",
    profileUrl: "https://kick.com/solem0",
    avatar: "",
    role: "",
  },
  {
    id: "s28",
    channelName: "ny",
    character: "",
    platform: "kick",
    channelId: "nymvia",
    profileUrl: "https://kick.com/nymvia",
    avatar: "",
    role: "",
  },
  {
    id: "s29",
    channelName: "Berru",
    character: "",
    platform: "kick",
    channelId: "berrusyy",
    profileUrl: "https://kick.com/berrusyy",
    avatar: "",
    role: "",
  },
  {
    id: "s30",
    channelName: "BARANCAN POLAT",
    character: "",
    platform: "kick",
    channelId: "antevor",
    profileUrl: "https://kick.com/antevor",
    avatar: "",
    role: "",
  },
  {
    id: "s31",
    channelName: "Wejfa",
    character: "",
    platform: "kick",
    channelId: "wejfaisback",
    profileUrl: "https://kick.com/wejfaisback",
    avatar: "",
    role: "",
  },
  {
    id: "s32",
    channelName: "theflyingtractor",
    character: "",
    platform: "kick",
    channelId: "theflyingtractor",
    profileUrl: "https://kick.com/theflyingtractor",
    avatar: "",
    role: "",
  },
  {
    id: "s33",
    channelName: "pinar",
    character: "",
    platform: "kick",
    channelId: "pinaroma",
    profileUrl: "https://kick.com/pinaroma",
    avatar: "",
    role: "",
  },
  {
    id: "s34",
    channelName: "Enes",
    character: "",
    platform: "kick",
    channelId: "urganci",
    profileUrl: "https://kick.com/urganci",
    avatar: "",
    role: "",
  },
  {
    id: "s35",
    channelName: "başıaçık",
    character: "",
    platform: "kick",
    channelId: "basiacik",
    profileUrl: "https://kick.com/basiacik",
    avatar: "",
    role: "",
  },
  {
    id: "s36",
    channelName: "dr.uzun",
    character: "",
    platform: "kick",
    channelId: "noisethegoosie",
    profileUrl: "https://kick.com/noisethegoosie",
    avatar: "",
    role: "",
  },
  {
    id: "s37",
    channelName: "Lythash",
    character: "",
    platform: "kick",
    channelId: "luythush",
    profileUrl: "https://kick.com/luythush",
    avatar: "",
    role: "",
  },
  {
    id: "s38",
    channelName: "Aslox",
    character: "",
    platform: "kick",
    channelId: "asloxen",
    profileUrl: "https://kick.com/asloxen",
    avatar: "",
    role: "",
  },
  {
    id: "s39",
    channelName: "Arzemien",
    character: "",
    platform: "kick",
    channelId: "arzemien",
    profileUrl: "https://kick.com/arzemien",
    avatar: "",
    role: "",
  },
  {
    id: "s40",
    channelName: "CagRez",
    character: "",
    platform: "kick",
    channelId: "cagrez",
    profileUrl: "https://kick.com/cagrez",
    avatar: "",
    role: "",
  },
  {
    id: "s41",
    channelName: "isagrimess",
    character: "",
    platform: "kick",
    channelId: "isagrimess",
    profileUrl: "https://kick.com/isagrimess",
    avatar: "",
    role: "",
  },
  {
    id: "s42",
    channelName: "EfeBerkSS",
    character: "",
    platform: "kick",
    channelId: "efeberkss",
    profileUrl: "https://kick.com/efeberkss",
    avatar: "",
    role: "",
  },
  {
    id: "s43",
    channelName: "5etul",
    character: "",
    platform: "kick",
    channelId: "5etul",
    profileUrl: "https://kick.com/5etul",
    avatar: "",
    role: "",
  },
  {
    id: "s44",
    channelName: "Desconden",
    character: "",
    platform: "kick",
    channelId: "desconden",
    profileUrl: "https://kick.com/desconden",
    avatar: "",
    role: "",
  },
  {
    id: "s45",
    channelName: "Crebros",
    character: "",
    platform: "kick",
    channelId: "crebros",
    profileUrl: "https://kick.com/crebros",
    avatar: "",
    role: "",
  },
  {
    id: "s46",
    channelName: "asmin",
    character: "",
    platform: "kick",
    channelId: "asminx",
    profileUrl: "https://kick.com/asminx",
    avatar: "",
    role: "",
  },
  {
    id: "s47",
    channelName: "Pudu",
    character: "",
    platform: "kick",
    channelId: "puducuk",
    profileUrl: "https://kick.com/puducuk",
    avatar: "",
    role: "",
  },
  {
    id: "s48",
    channelName: "k0ffie",
    character: "",
    platform: "kick",
    channelId: "k0ffie",
    profileUrl: "https://kick.com/k0ffie",
    avatar: "",
    role: "",
  },
  {
    id: "s49",
    channelName: "Eudae",
    character: "",
    platform: "kick",
    channelId: "ruubina",
    profileUrl: "https://kick.com/ruubina",
    avatar: "",
    role: "",
  },
  {
    id: "s50",
    channelName: "Dilahoo",
    character: "",
    platform: "kick",
    channelId: "dilahoo",
    profileUrl: "https://kick.com/dilahoo",
    avatar: "",
    role: "",
  },
  {
    id: "s51",
    channelName: "CüCeBeBe",
    character: "",
    platform: "kick",
    channelId: "cucebebe",
    profileUrl: "https://kick.com/cucebebe",
    avatar: "",
    role: "",
  },
  {
    id: "s52",
    channelName: "kl3sty",
    character: "",
    platform: "kick",
    channelId: "kl3sty",
    profileUrl: "https://kick.com/kl3sty",
    avatar: "",
    role: "",
  },
  {
    id: "s53",
    channelName: "HobbitEmo",
    character: "",
    platform: "kick",
    channelId: "hobbitemo",
    profileUrl: "https://kick.com/hobbitemo",
    avatar: "",
    role: "",
  },
];

// ─── Bildir formu bu adrese gider ────────────
// Kendi mail adresini yaz!
const CONTACT_EMAIL = "knglrp@gmail.com";
